import { Router, type IRouter } from "express";
import {
  db, settlementsTable, projectsTable, usersTable, paymentsTable, companiesTable,
  translatorSensitiveTable,
} from "@workspace/db";
import { eq, inArray, and, lte, sql } from "drizzle-orm";
import { requireAuth, requireRole, requirePermission } from "../middlewares/auth";
import { logEvent } from "../lib/logEvent";

const router: IRouter = Router();
const adminGuard = [requireAuth, requireRole("admin", "staff")];

// ── 정산 요약 통계 ─────────────────────────────────────────────────────────────
router.get("/admin/settlements/summary", ...adminGuard, async (req, res) => {
  try {
    const today = new Date().toISOString().slice(0, 10);

    const rows = await db
      .select({
        status: settlementsTable.status,
        payoutDueDate: settlementsTable.payoutDueDate,
        netAmount: settlementsTable.netAmount,
        translatorAmount: settlementsTable.translatorAmount,
      })
      .from(settlementsTable);

    let dueTodayCount = 0;
    let readyCount = 0;
    let pendingReviewCount = 0;
    let paidCount = 0;
    let overdueCount = 0;

    for (const r of rows) {
      if (r.status === "paid") { paidCount++; continue; }
      if (r.status === "ready") readyCount++;
      if (r.status === "pending_review") pendingReviewCount++;
      if (r.payoutDueDate) {
        if (r.payoutDueDate <= today && r.status !== "paid") overdueCount++;
        if (r.payoutDueDate === today) dueTodayCount++;
      }
    }

    res.json({ dueTodayCount, readyCount, pendingReviewCount, paidCount, overdueCount, total: rows.length });
  } catch (err) {
    req.log.error({ err }, "Admin: failed to fetch settlement summary");
    res.status(500).json({ error: "정산 요약 조회 실패." });
  }
});

// ── 정산 목록 ─────────────────────────────────────────────────────────────────
router.get("/admin/settlements", ...adminGuard, async (req, res) => {
  try {
    const rows = await db
      .select({
        id: settlementsTable.id,
        projectId: settlementsTable.projectId,
        taskId: settlementsTable.taskId,
        translatorId: settlementsTable.translatorId,
        paymentId: settlementsTable.paymentId,
        translatorName: settlementsTable.translatorName,
        translatorNameFromUser: usersTable.name,

        totalAmount: settlementsTable.totalAmount,
        translatorAmount: settlementsTable.translatorAmount,
        platformFee: settlementsTable.platformFee,
        grossAmount: settlementsTable.grossAmount,
        netAmount: settlementsTable.netAmount,

        settlementType: settlementsTable.settlementType,
        withholdingRate: settlementsTable.withholdingRate,
        withholdingAmount: settlementsTable.withholdingAmount,
        vatAmount: settlementsTable.vatAmount,

        paymentMethod: settlementsTable.paymentMethod,
        payoutDueDate: settlementsTable.payoutDueDate,

        status: settlementsTable.status,
        reviewReason: settlementsTable.reviewReason,
        isAutoGenerated: settlementsTable.isAutoGenerated,

        paidDate: settlementsTable.paidDate,
        paidAt: settlementsTable.paidAt,
        paymentMemo: settlementsTable.paymentMemo,
        createdAt: settlementsTable.createdAt,

        projectTitle: projectsTable.title,
        translatorEmail: usersTable.email,
        companyName: companiesTable.name,
      })
      .from(settlementsTable)
      .leftJoin(projectsTable, eq(settlementsTable.projectId, projectsTable.id))
      .leftJoin(companiesTable, eq(projectsTable.companyId, companiesTable.id))
      .leftJoin(usersTable, eq(settlementsTable.translatorId, usersTable.id))
      .orderBy(settlementsTable.payoutDueDate, settlementsTable.createdAt);

    // translatorName 병합: settlements.translatorName → users.name 순으로 fallback
    const merged = rows.map(r => ({
      ...r,
      translatorName: r.translatorName ?? r.translatorNameFromUser ?? null,
      translatorNameFromUser: undefined, // 클라이언트 노출 불필요
    }));

    // 정렬: 1순위 status, 2순위 payoutDueDate, 3순위 translatorName
    const order = ["pending_review", "ready", "draft", "pending", "paid"];
    const sorted = [...merged].sort((a, b) => {
      const ai = order.indexOf(a.status ?? "pending");
      const bi = order.indexOf(b.status ?? "pending");
      if (ai !== bi) return ai - bi;
      // 지급 예정일 빠른순 (null 후순위)
      const da = a.payoutDueDate ?? "9999-12-31";
      const db = b.payoutDueDate ?? "9999-12-31";
      if (da !== db) return da.localeCompare(db);
      // 이름 가나다순
      const na = (a.translatorName ?? a.translatorEmail ?? "").toLowerCase();
      const nb = (b.translatorName ?? b.translatorEmail ?? "").toLowerCase();
      return na.localeCompare(nb, "ko");
    });

    res.json(sorted);
  } catch (err) {
    req.log.error({ err }, "Admin: failed to fetch settlements");
    res.status(500).json({ error: "정산 목록 조회 실패." });
  }
});

// ── pending_review → ready 승인 ────────────────────────────────────────────────
router.patch("/admin/settlements/:id/approve",
  ...adminGuard,
  async (req, res) => {
    const settlementId = Number(req.params.id);
    if (isNaN(settlementId) || settlementId <= 0) {
      res.status(400).json({ error: "유효하지 않은 settlement id." });
      return;
    }

    const [settlement] = await db
      .select()
      .from(settlementsTable)
      .where(eq(settlementsTable.id, settlementId));

    if (!settlement) {
      res.status(404).json({ error: `Settlement ${settlementId} not found.` });
      return;
    }
    if (settlement.status === "paid") {
      res.status(400).json({ error: "이미 지급 완료된 건입니다." });
      return;
    }
    if (settlement.status === "ready") {
      res.status(400).json({ error: "이미 ready 상태입니다." });
      return;
    }

    try {
      const { memo } = req.body as { memo?: string };
      const [updated] = await db
        .update(settlementsTable)
        .set({
          status: "ready",
          reviewReason: null,
          paymentMemo: memo?.trim() || settlement.paymentMemo,
        })
        .where(eq(settlementsTable.id, settlementId))
        .returning();

      await logEvent("project", settlement.projectId, "settlement_marked_ready", req.log);
      res.json(updated);
    } catch (err) {
      req.log.error({ err }, "Failed to approve settlement");
      res.status(500).json({ error: "정산 승인 처리 실패." });
    }
  }
);

// ── 단건 지급 완료 처리 ───────────────────────────────────────────────────────
router.patch("/admin/settlements/:id/pay",
  ...adminGuard,
  requirePermission("settlement.pay"),
  async (req, res) => {
    const settlementId = Number(req.params.id);
    if (isNaN(settlementId) || settlementId <= 0) {
      res.status(400).json({ error: "유효하지 않은 settlement id." });
      return;
    }

    const [settlement] = await db
      .select()
      .from(settlementsTable)
      .where(eq(settlementsTable.id, settlementId));

    if (!settlement) {
      res.status(404).json({ error: `Settlement ${settlementId} not found.` });
      return;
    }
    if (settlement.status === "paid") {
      res.status(400).json({ error: "이미 정산 완료된 건입니다." });
      return;
    }
    if (settlement.status !== "ready") {
      res.status(400).json({ error: `정산 완료 처리는 "ready" 상태에서만 가능합니다. 현재: "${settlement.status}"` });
      return;
    }

    try {
      const paymentMemo = typeof req.body?.paymentMemo === "string" ? req.body.paymentMemo.trim() || null : null;
      const now = new Date();

      const [updated] = await db
        .update(settlementsTable)
        .set({ status: "paid", paidDate: now, paidAt: now, paymentMemo })
        .where(eq(settlementsTable.id, settlementId))
        .returning();

      await logEvent("project", settlement.projectId, "settlement_paid", req.log);
      res.json(updated);
    } catch (err) {
      req.log.error({ err }, "Failed to pay settlement");
      res.status(500).json({ error: "정산 완료 처리 실패." });
    }
  }
);

// ── 일괄 지급 완료 처리 ───────────────────────────────────────────────────────
router.patch("/admin/settlements/batch-pay",
  ...adminGuard,
  requirePermission("settlement.pay"),
  async (req, res) => {
    const { ids, paymentMemo } = req.body as { ids?: unknown; paymentMemo?: unknown };

    if (!Array.isArray(ids) || ids.length === 0) {
      res.status(400).json({ error: "ids 배열이 필요합니다." });
      return;
    }

    const validIds = ids.map(Number).filter(n => !isNaN(n) && n > 0);
    if (validIds.length === 0) {
      res.status(400).json({ error: "유효한 id가 없습니다." });
      return;
    }

    const memo = typeof paymentMemo === "string" ? paymentMemo.trim() || null : null;

    try {
      const targets = await db
        .select({ id: settlementsTable.id, projectId: settlementsTable.projectId, status: settlementsTable.status })
        .from(settlementsTable)
        .where(inArray(settlementsTable.id, validIds));

      const readyIds = targets.filter(t => t.status === "ready").map(t => t.id);

      if (readyIds.length === 0) {
        res.status(400).json({ error: "지급 처리 가능한(ready 상태) 정산 건이 없습니다." });
        return;
      }

      const now = new Date();
      const updated = await db
        .update(settlementsTable)
        .set({ status: "paid", paidDate: now, paidAt: now, paymentMemo: memo })
        .where(inArray(settlementsTable.id, readyIds))
        .returning();

      for (const t of targets.filter(t => readyIds.includes(t.id))) {
        await logEvent("project", t.projectId, "settlement_paid", req.log);
      }

      res.json({ updated: updated.length, skipped: validIds.length - readyIds.length, items: updated });
    } catch (err) {
      req.log.error({ err }, "Failed to batch-pay settlements");
      res.status(500).json({ error: "일괄 정산 처리 실패." });
    }
  }
);

// ── 일괄 지급 완료 (bulk-pay) ─────────────────────────────────────────────────
router.post("/admin/settlements/bulk-pay", ...adminGuard, async (req, res) => {
  const rawIds: number[] = req.body?.settlementIds ?? [];
  if (!Array.isArray(rawIds) || rawIds.length === 0) {
    res.status(400).json({ error: "settlementIds 필드가 필요합니다." });
    return;
  }
  const validIds = rawIds.filter(id => Number.isInteger(id) && id > 0);
  try {
    const targets = await db
      .select({ id: settlementsTable.id, projectId: settlementsTable.projectId, status: settlementsTable.status })
      .from(settlementsTable)
      .where(inArray(settlementsTable.id, validIds));

    const readyIds = targets.filter(t => t.status === "ready").map(t => t.id);
    if (readyIds.length === 0) {
      res.status(400).json({ error: "지급 가능한 항목이 없습니다. ready 상태만 지급 처리할 수 있습니다." });
      return;
    }

    const now = new Date();
    const updated = await db
      .update(settlementsTable)
      .set({ status: "paid", paidAt: now, paidDate: now.toISOString().slice(0, 10) })
      .where(inArray(settlementsTable.id, readyIds))
      .returning({ id: settlementsTable.id });

    for (const t of targets.filter(t => readyIds.includes(t.id))) {
      await logEvent("project", t.projectId, "settlement_paid_bulk", req.log);
    }

    res.json({
      updated: updated.length,
      skipped: validIds.length - readyIds.length,
      items: updated,
    });
  } catch (err) {
    req.log.error({ err }, "Failed to bulk-pay settlements");
    res.status(500).json({ error: "일괄 지급 처리 실패." });
  }
});

// ── 지급 파일 내보내기 CSV ─────────────────────────────────────────────────────
router.get("/admin/settlements/export", ...adminGuard, async (req, res) => {
  const rawIds = String(req.query.ids ?? "");
  const ids = rawIds
    .split(",")
    .map(s => parseInt(s.trim(), 10))
    .filter(n => !isNaN(n) && n > 0);

  if (ids.length === 0) {
    res.status(400).json({ error: "ids 쿼리 파라미터가 필요합니다. 예: ?ids=1,2,3" });
    return;
  }

  try {
    const rows = await db
      .select({
        id: settlementsTable.id,
        translatorName: settlementsTable.translatorName,
        netAmount: settlementsTable.netAmount,
        payoutDueDate: settlementsTable.payoutDueDate,
        bankName: translatorSensitiveTable.bankName,
        bankAccount: translatorSensitiveTable.bankAccount,
        accountHolder: translatorSensitiveTable.accountHolder,
        paypalEmail: translatorSensitiveTable.paypalEmail,
        paymentMethod: translatorSensitiveTable.paymentMethod,
        status: settlementsTable.status,
      })
      .from(settlementsTable)
      .leftJoin(
        translatorSensitiveTable,
        eq(settlementsTable.translatorId, translatorSensitiveTable.translatorId),
      )
      .where(inArray(settlementsTable.id, ids));

    const header = ["정산ID", "번역사 이름", "은행명", "계좌번호", "예금주", "실지급액", "지급 예정일", "상태"];
    const csvLines = [
      header.join(","),
      ...rows.map(r => [
        r.id,
        `"${(r.translatorName ?? "").replace(/"/g, '""')}"`,
        `"${(r.bankName ?? (r.paypalEmail ? "PayPal" : "")).replace(/"/g, '""')}"`,
        `"${(r.bankAccount ?? r.paypalEmail ?? "").replace(/"/g, '""')}"`,
        `"${(r.accountHolder ?? "").replace(/"/g, '""')}"`,
        r.netAmount ?? 0,
        r.payoutDueDate ?? "",
        r.status ?? "",
      ].join(",")),
    ];

    const csvContent = "\uFEFF" + csvLines.join("\r\n"); // UTF-8 BOM for Excel
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="payment_${new Date().toISOString().slice(0, 10)}.csv"`,
    );
    res.send(csvContent);
  } catch (err) {
    req.log.error({ err }, "Failed to export settlements CSV");
    res.status(500).json({ error: "지급 파일 생성 실패." });
  }
});

// ── 번역사 본인 정산 내역 ──────────────────────────────────────────────────────
router.get("/settlements/my", requireAuth, requireRole("translator"), async (req, res) => {
  const translatorId = req.user!.id;
  try {
    const rows = await db
      .select({
        id: settlementsTable.id,
        projectId: settlementsTable.projectId,
        totalAmount: settlementsTable.totalAmount,
        translatorAmount: settlementsTable.translatorAmount,
        platformFee: settlementsTable.platformFee,
        grossAmount: settlementsTable.grossAmount,
        netAmount: settlementsTable.netAmount,
        settlementType: settlementsTable.settlementType,
        withholdingAmount: settlementsTable.withholdingAmount,
        payoutDueDate: settlementsTable.payoutDueDate,
        status: settlementsTable.status,
        reviewReason: settlementsTable.reviewReason,
        paidDate: settlementsTable.paidDate,
        paidAt: settlementsTable.paidAt,
        createdAt: settlementsTable.createdAt,
        projectTitle: projectsTable.title,
      })
      .from(settlementsTable)
      .leftJoin(projectsTable, eq(settlementsTable.projectId, projectsTable.id))
      .where(eq(settlementsTable.translatorId, translatorId))
      .orderBy(settlementsTable.createdAt);

    res.json(rows.reverse());
  } catch (err) {
    req.log.error({ err }, "Translator: failed to fetch settlements");
    res.status(500).json({ error: "정산 내역 조회 실패." });
  }
});

export default router;
