// 컨트롤타워 탭 — 상태 기반 UX 자동 제어 (2025-04)
import React, { useCallback, useEffect, useState } from "react";
import { api, FINANCIAL_STATUS_LABEL, FINANCIAL_STATUS_STYLE } from "../../lib/constants";
import { StatusBadge } from "../ui";

// ── 타입 ─────────────────────────────────────────────────────────────────────
interface ControlTowerData {
  project: {
    id: number; title: string; status: string; financialStatus: string;
    createdAt: string; companyId: number | null;
    requestingCompanyName?: string | null; billingCompanyName?: string | null;
    payerCompanyName?: string | null; divisionName?: string | null;
    customerEmail?: string | null;
  };
  company:  { id: number; name: string; email?: string | null; phone?: string | null } | null;
  contact:  { id: number; name: string; email?: string | null; phone?: string | null } | null;
  summary: {
    saleSupplyAmount: number; saleTaxAmount: number; saleTotalAmount: number;
    totalPayoutAmount: number; estimatedMargin: number;
    paidAmount: number; unpaidAmount: number;
    paymentStatus: "fully_paid" | "partial" | "unpaid";
    settlementStatus: "all_paid" | "partial" | "pending_review" | "pending";
    translatorCount: number; doneTaskCount: number;
  };
  quotes: Array<{
    id: number; price: string; status: string; quoteType: string; billingType: string;
    issueDate?: string | null; invoiceDueDate?: string | null; paymentDueDate?: string | null;
    items: Array<{
      id: number; productName: string; languagePair?: string | null; unit: string;
      quantity: string; unitPrice: string; supplyAmount: string; taxAmount: string;
      totalAmount: string; memo?: string | null;
    }>;
  }>;
  payments: Array<{
    id: number; amount: string; status: string; paymentMethod?: string | null; createdAt: string;
  }>;
  translators: Array<{
    userId: number; name?: string | null; email?: string | null;
    taskId: number; taskStatus: string; taskCreatedAt: string;
    deliveryDate: string | null;
    settlement: {
      id: number; grossAmount: string | null; netAmount: string | null;
      withholdingAmount: string | null; vatAmount: string | null;
      settlementType: string | null; payoutDueDate: string | null;
      status: string; paidAt: string | null; reviewReason: string | null;
      isAutoGenerated: boolean | null;
    } | null;
  }>;
}

interface Props {
  projectId: number;
  token: string;
  onToast: (msg: string) => void;
  onOpenQuoteForm: () => void;
  onOpenPaymentForm: () => void;
  onOpenAssignPanel: () => void;
  onGoToFinance: () => void;
}

// ── 포맷 헬퍼 ────────────────────────────────────────────────────────────────
const fmtWon  = (n: number) => `₩${Math.round(n).toLocaleString()}`;
const fmtDate = (d?: string | null) => d ? d.slice(0, 10) : "—";
const fmtMD   = (d?: string | null) => d ? d.slice(5, 10).replace("-", ".") : "—";

// ── 공통 스타일 상수 ──────────────────────────────────────────────────────────
const card: React.CSSProperties = {
  background: "#fff", border: "1px solid #e5e7eb", borderRadius: 12,
  padding: "14px 18px", position: "relative", overflow: "hidden",
};
const sectionHd: React.CSSProperties = {
  fontSize: 13, fontWeight: 700, color: "#111827", margin: 0,
  paddingBottom: 8, borderBottom: "1px solid #f3f4f6",
  display: "flex", alignItems: "center", justifyContent: "space-between",
};
const TH: React.CSSProperties = {
  padding: "8px 10px", fontSize: 11, fontWeight: 700, color: "#6b7280",
  background: "#f9fafb", borderBottom: "1px solid #e5e7eb",
  textAlign: "left" as const, whiteSpace: "nowrap" as const,
};
const TD: React.CSSProperties = {
  padding: "9px 10px", fontSize: 12, color: "#374151",
  borderBottom: "1px solid #f3f4f6", verticalAlign: "top" as const,
};
const primaryBtn = (extra: React.CSSProperties = {}): React.CSSProperties => ({
  padding: "6px 14px", borderRadius: 7, fontSize: 12, fontWeight: 700,
  cursor: "pointer", border: "none", whiteSpace: "nowrap" as const,
  background: "#2563eb", color: "#fff", ...extra,
});
const ghostBtn: React.CSSProperties = {
  padding: "5px 10px", borderRadius: 6, fontSize: 11, fontWeight: 600,
  cursor: "pointer", background: "#f9fafb", border: "1px solid #e5e7eb",
  color: "#374151", whiteSpace: "nowrap" as const,
};

// ── 참조 데이터 ───────────────────────────────────────────────────────────────
const SETTLE_STATUS_BADGE: Record<string, React.CSSProperties> = {
  paid:           { background: "#dcfce7", color: "#15803d" },
  ready:          { background: "#d1fae5", color: "#059669" },
  pending_review: { background: "#fef3c7", color: "#b45309" },
  pending:        { background: "#f3f4f6", color: "#6b7280" },
  draft:          { background: "#f1f5f9", color: "#94a3b8" },
};
const SETTLE_STATUS_KO: Record<string, string> = {
  paid: "지급 완료", ready: "지급 준비", pending_review: "검토 필요",
  pending: "대기", draft: "정보 부족",
};
const SETTLEMENT_TYPE_KO: Record<string, string> = {
  WITHHOLDING_3_3: "원천세 3.3%", VAT_INVOICE: "세금계산서",
  OVERSEAS_REMITTANCE: "해외송금", OTHER_REVIEW: "기타",
};
const SETTLEMENT_TYPE_STYLE: Record<string, React.CSSProperties> = {
  WITHHOLDING_3_3:     { background: "#ede9fe", color: "#7c3aed" },
  VAT_INVOICE:         { background: "#dbeafe", color: "#2563eb" },
  OVERSEAS_REMITTANCE: { background: "#fef3c7", color: "#b45309" },
  OTHER_REVIEW:        { background: "#f3f4f6", color: "#6b7280" },
};
const QUOTE_TYPE_KO: Record<string, string> = {
  b2b_standard: "일반 B2B", b2c_prepaid: "선입금",
  prepaid_deduction: "선입금 차감", accumulated_batch: "누적 청구",
};

// ── 빈 상태 CTA ───────────────────────────────────────────────────────────────
function EmptyCTA({ icon, text, btnLabel, onClick, disabled }: {
  icon: string; text: string; btnLabel: string; onClick: () => void; disabled?: boolean;
}) {
  return (
    <div style={{ textAlign: "center", padding: "24px 16px", background: "#f9fafb", borderRadius: 8, border: "1px dashed #d1d5db" }}>
      <div style={{ fontSize: 30, marginBottom: 8 }}>{icon}</div>
      <p style={{ margin: "0 0 12px", fontSize: 13, color: "#6b7280" }}>{text}</p>
      <button onClick={onClick} disabled={disabled}
        style={primaryBtn({ opacity: disabled ? 0.5 : 1 })}>
        {btnLabel}
      </button>
    </div>
  );
}

// ── 메인 컴포넌트 ─────────────────────────────────────────────────────────────
export function ProjectControlTowerTab({
  projectId, token, onToast,
  onOpenQuoteForm, onOpenPaymentForm, onOpenAssignPanel, onGoToFinance,
}: Props) {
  const [data, setData]   = useState<ControlTowerData | null>(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr]     = useState("");
  const [payingId, setPayingId] = useState<number | null>(null);

  const fetchData = useCallback(() => {
    setLoading(true); setErr("");
    fetch(api(`/api/admin/projects/${projectId}/control-tower`), {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then(r => r.json())
      .then(d => { if (d.error) throw new Error(d.error); setData(d); })
      .catch(e => setErr(e.message ?? "데이터 조회 실패"))
      .finally(() => setLoading(false));
  }, [projectId, token]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // ── 지급 처리 ──────────────────────────────────────────────────────────────
  const handlePay = async (settlementId: number) => {
    if (!confirm("이 정산건을 지급 완료 처리하시겠습니까?")) return;
    setPayingId(settlementId);
    try {
      const res = await fetch(api(`/api/admin/settlements/${settlementId}/pay`), {
        method: "PATCH",
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || "지급 처리 실패");
      onToast("지급 완료 처리되었습니다."); fetchData();
    } catch (e: any) { onToast(`오류: ${e.message}`); }
    finally { setPayingId(null); }
  };

  if (loading) return <div style={{ padding: 32, textAlign: "center", color: "#9ca3af" }}>불러오는 중...</div>;
  if (err || !data) return <div style={{ padding: 32, textAlign: "center", color: "#dc2626" }}>{err || "데이터 없음"}</div>;

  const { project, company, contact, summary, quotes, payments, translators } = data;
  const today = new Date().toISOString().slice(0, 10);

  // ── 핵심 상태 파생 ────────────────────────────────────────────────────────
  const hasQuotes       = quotes.length > 0;
  const hasTranslators  = translators.length > 0;
  const hasPayments     = payments.length > 0;
  const isFullyPaid     = summary.paymentStatus === "fully_paid";
  const hasSettlements  = translators.some(t => t.settlement !== null);
  const hasPayableSettlement = translators.some(
    t => t.settlement?.status === "ready" || t.settlement?.status === "pending"
  );
  const allSettlementsPaid   = hasSettlements && translators
    .filter(t => t.settlement !== null)
    .every(t => t.settlement!.status === "paid");

  // ── 글로벌 배너 메시지 (우선순위 기반) ───────────────────────────────────
  const needsItems: string[] = [];
  if (!hasQuotes)      needsItems.push("견적");
  if (!hasTranslators) needsItems.push("배정");
  // 결제/지급은 섹션 전용 (상단 배너에 표시하지 않음)

  const showBanner = needsItems.length > 0;
  const bannerMsg  = needsItems.length === 1
    ? `${needsItems[0]}이 필요합니다`
    : `${needsItems.join(" / ")}이 필요합니다`;

  // ── 글로벌 액션 버튼 (최대 2개, 흐름 시작 전용) ──────────────────────────
  const topActions: Array<{ label: string; bg: string; onClick: () => void }> = [];
  if (!hasQuotes)
    topActions.push({ label: "📋 견적 생성", bg: "#2563eb", onClick: onOpenQuoteForm });
  if (!hasTranslators && topActions.length < 2)
    topActions.push({ label: "👤 통번역사 배정", bg: "#7c3aed", onClick: onOpenAssignPanel });

  // ── 요약 카드 값 계산 ─────────────────────────────────────────────────────
  const payBadge = (() => {
    if (isFullyPaid)                          return { label: "결제 완료", bg: "#dcfce7", color: "#15803d" };
    if (summary.paymentStatus === "partial")  return { label: "부분 입금", bg: "#fef3c7", color: "#b45309" };
    return { label: "미결제", bg: "#fee2e2", color: "#dc2626" };
  })();
  const settleBadge = (() => {
    if (allSettlementsPaid)                              return { label: "지급 완료",  bg: "#dcfce7", color: "#15803d" };
    if (summary.settlementStatus === "partial")          return { label: "일부 지급",  bg: "#d1fae5", color: "#059669" };
    if (summary.settlementStatus === "pending_review")   return { label: "검토 필요",  bg: "#fef3c7", color: "#b45309" };
    if (!hasSettlements)                                 return { label: "미생성",     bg: "#f3f4f6", color: "#9ca3af" };
    return { label: "미지급", bg: "#fee2e2", color: "#dc2626" };
  })();

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

      {/* ── 프로젝트 헤더 ────────────────────────────────────────────────────── */}
      <div style={{ ...card, background: "linear-gradient(135deg, #f8faff, #eff6ff)", borderColor: "#bfdbfe" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: "linear-gradient(90deg, #3b82f6, #8b5cf6)" }} />
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: 8 }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 800, color: "#111827", marginBottom: 4 }}>{project.title}</div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", fontSize: 12, color: "#6b7280" }}>
              {company && <span>🏢 {company.name}</span>}
              {project.divisionName && <span>· 📂 {project.divisionName}</span>}
              {project.billingCompanyName && project.billingCompanyName !== company?.name && (
                <span>· 📄 청구: {project.billingCompanyName}</span>
              )}
              {contact && <span>· 👤 {contact.name}</span>}
              <span>· 📅 {fmtDate(project.createdAt)}</span>
            </div>
          </div>
          <div style={{ display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" }}>
            <StatusBadge status={project.status} />
            <span style={{
              padding: "3px 8px", borderRadius: 6, fontSize: 11, fontWeight: 600,
              ...(FINANCIAL_STATUS_STYLE[project.financialStatus] ?? { background: "#f3f4f6", color: "#6b7280" }),
            }}>
              {FINANCIAL_STATUS_LABEL[project.financialStatus] ?? project.financialStatus}
            </span>
          </div>
        </div>
      </div>

      {/* ── 글로벌 배너 (흐름 시작 액션) ─────────────────────────────────────── */}
      {showBanner && (
        <div style={{
          background: "#fffbeb", border: "1.5px solid #fcd34d", borderRadius: 10,
          padding: "11px 16px", display: "flex", alignItems: "center",
          gap: 12, flexWrap: "wrap",
        }}>
          <span style={{ fontSize: 22 }}>⚠️</span>
          <span style={{ fontSize: 13, fontWeight: 700, color: "#92400e", flex: 1 }}>
            {bannerMsg}
          </span>
          {topActions.map((a, i) => (
            <button key={i} onClick={a.onClick}
              style={{
                padding: "7px 16px", borderRadius: 7, fontSize: 12, fontWeight: 700,
                cursor: "pointer", background: a.bg, color: "#fff", border: "none",
              }}>
              {a.label}
            </button>
          ))}
        </div>
      )}

      {/* ── 요약 카드 5개 ─────────────────────────────────────────────────────── */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 10 }}>
        {/* 판매금액 */}
        <SCard topColor={hasQuotes ? "#3b82f6" : "#d1d5db"} label="판매금액"
          main={hasQuotes ? fmtWon(summary.saleTotalAmount) : "미등록"}
          mainColor={hasQuotes ? "#111827" : "#9ca3af"}
          sub={hasQuotes && summary.saleTaxAmount > 0
            ? `공급가 ${fmtWon(summary.saleSupplyAmount)} + 세금 ${fmtWon(summary.saleTaxAmount)}`
            : hasQuotes ? "부가세 없음" : "견적 등록이 필요합니다"}
        />
        {/* 지급예정액 */}
        <SCard topColor={hasSettlements ? "#8b5cf6" : "#d1d5db"} label="지급예정액"
          main={hasSettlements ? fmtWon(summary.totalPayoutAmount) : "없음"}
          mainColor={hasSettlements ? "#111827" : "#9ca3af"}
          sub={hasSettlements
            ? `번역사 ${summary.translatorCount}명 (${summary.doneTaskCount}건 완료)`
            : "정산 생성 전"}
        />
        {/* 예상 차액 */}
        <SCard
          topColor={!hasQuotes ? "#d1d5db" : summary.estimatedMargin >= 0 ? "#059669" : "#dc2626"}
          label="예상 차액"
          main={!hasQuotes ? "—" : (summary.estimatedMargin >= 0 ? "+" : "") + fmtWon(summary.estimatedMargin)}
          mainColor={!hasQuotes ? "#9ca3af" : summary.estimatedMargin >= 0 ? "#059669" : "#dc2626"}
          sub={hasQuotes && summary.saleTotalAmount > 0
            ? `마진율 ${Math.round((summary.estimatedMargin / summary.saleTotalAmount) * 100)}%`
            : undefined}
        />
        {/* 고객 결제 */}
        <SCard topColor={payBadge.color} label="고객 결제"
          badge={payBadge}
          sub={`입금 ${fmtWon(summary.paidAmount)} / 미수 ${fmtWon(summary.unpaidAmount)}`}
        />
        {/* 지급 현황 */}
        <SCard topColor={settleBadge.color} label="지급 현황"
          badge={settleBadge}
          sub={hasSettlements
            ? `정산 ${translators.filter(t => t.settlement).length}/${translators.length}건`
            : "정산 없음"}
        />
      </div>

      {/* ── 판매정보 섹션 ─────────────────────────────────────────────────────── */}
      <div style={{ ...card, opacity: hasQuotes ? 1 : 0.65, transition: "opacity 0.2s" }}>
        <div style={{ ...sectionHd, marginBottom: 12 }}>
          <span>📋 판매정보</span>
          {hasQuotes ? (
            <button onClick={onGoToFinance} style={ghostBtn}>✏️ 견적 수정</button>
          ) : (
            <button onClick={onOpenQuoteForm}
              style={{ padding: "5px 12px", borderRadius: 7, fontSize: 11, fontWeight: 700, cursor: "pointer", border: "none", background: "#2563eb", color: "#fff" }}>
              ＋ 견적 생성
            </button>
          )}
        </div>
        {!hasQuotes ? (
          <EmptyCTA icon="📋" text="견적 정보가 없습니다." btnLabel="견적 생성하기" onClick={onOpenQuoteForm} />
        ) : (
          quotes.map(q => {
            const qSupply = q.items.reduce((s, i) => s + Number(i.supplyAmount ?? 0), 0);
            const qTax    = q.items.reduce((s, i) => s + Number(i.taxAmount    ?? 0), 0);
            const qTotal  = q.items.reduce((s, i) => s + Number(i.totalAmount  ?? 0), 0);
            return (
              <div key={q.id} style={{ marginBottom: 16 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8, flexWrap: "wrap" }}>
                  <span style={{ fontSize: 12, fontWeight: 600, color: "#374151" }}>견적 #{q.id}</span>
                  <StatusBadge status={q.status} />
                  <span style={{ padding: "2px 7px", borderRadius: 5, fontSize: 10, fontWeight: 600, background: "#f0f9ff", color: "#0369a1" }}>
                    {QUOTE_TYPE_KO[q.quoteType] ?? q.quoteType}
                  </span>
                  {q.issueDate      && <span style={{ fontSize: 11, color: "#9ca3af" }}>발행일: {q.issueDate}</span>}
                  {q.invoiceDueDate && <span style={{ fontSize: 11, color: "#9ca3af" }}>청구일: {q.invoiceDueDate}</span>}
                  {q.paymentDueDate && <span style={{ fontSize: 11, color: "#9ca3af" }}>입금예정: {q.paymentDueDate}</span>}
                </div>
                {q.items.length > 0 ? (
                  <div style={{ overflowX: "auto" }}>
                    <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
                      <thead>
                        <tr>{["상품/서비스","언어쌍","단위","수량","단가","공급가액","부가세","합계","비고"].map(h =>
                          <th key={h} style={TH}>{h}</th>
                        )}</tr>
                      </thead>
                      <tbody>
                        {q.items.map(item => (
                          <tr key={item.id}>
                            <td style={{ ...TD, fontWeight: 600, maxWidth: 140 }}>{item.productName}</td>
                            <td style={{ ...TD, color: "#6b7280" }}>{item.languagePair ?? "—"}</td>
                            <td style={{ ...TD, color: "#6b7280" }}>{item.unit}</td>
                            <td style={{ ...TD, textAlign: "right" as const }}>{Number(item.quantity).toLocaleString()}</td>
                            <td style={{ ...TD, textAlign: "right" as const }}>{Number(item.unitPrice).toLocaleString()}</td>
                            <td style={{ ...TD, textAlign: "right" as const, fontWeight: 600 }}>{Number(item.supplyAmount).toLocaleString()}</td>
                            <td style={{ ...TD, textAlign: "right" as const, color: "#b45309" }}>{Number(item.taxAmount).toLocaleString()}</td>
                            <td style={{ ...TD, textAlign: "right" as const, fontWeight: 700, color: "#1d4ed8" }}>{Number(item.totalAmount).toLocaleString()}</td>
                            <td style={{ ...TD, color: "#9ca3af", maxWidth: 120 }}>{item.memo ?? "—"}</td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot>
                        <tr style={{ background: "#f9fafb" }}>
                          <td colSpan={5} style={{ ...TD, fontWeight: 700 }}>합계</td>
                          <td style={{ ...TD, textAlign: "right" as const, fontWeight: 700 }}>{qSupply.toLocaleString()}</td>
                          <td style={{ ...TD, textAlign: "right" as const, fontWeight: 700, color: "#b45309" }}>{qTax.toLocaleString()}</td>
                          <td style={{ ...TD, textAlign: "right" as const, fontWeight: 800, color: "#1d4ed8" }}>{qTotal.toLocaleString()}</td>
                          <td style={TD} />
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                ) : (
                  <p style={{ fontSize: 12, color: "#9ca3af", margin: 0 }}>
                    견적 금액: {Number(q.price).toLocaleString()}원 (상세 아이템 없음)
                  </p>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* ── 통번역사 수행/정산 섹션 ──────────────────────────────────────────── */}
      <div style={card}>
        <div style={{ ...sectionHd, marginBottom: 12 }}>
          <span>👥 통번역사 수행 · 정산</span>
          {!hasTranslators ? (
            <button onClick={onOpenAssignPanel}
              style={{ padding: "5px 12px", borderRadius: 7, fontSize: 11, fontWeight: 700, cursor: "pointer", border: "none", background: "#7c3aed", color: "#fff" }}>
              ＋ 통번역사 배정
            </button>
          ) : (
            <button onClick={onOpenAssignPanel} style={ghostBtn}>➕ 추가 배정</button>
          )}
        </div>

        {!hasTranslators ? (
          <EmptyCTA icon="👤" text="배정된 통번역사가 없습니다." btnLabel="통번역사 배정하기" onClick={onOpenAssignPanel} />
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr>{["통번역사","태스크 상태","납품일","지급예정일","원금액","원천세","실지급액","정산 유형","정산 상태","액션"].map(h =>
                  <th key={h} style={TH}>{h}</th>
                )}</tr>
              </thead>
              <tbody>
                {translators.map(t => {
                  const s           = t.settlement;
                  const gross       = Number(s?.grossAmount       ?? 0);
                  const withholding = Number(s?.withholdingAmount  ?? 0);
                  const net         = Number(s?.netAmount          ?? 0);
                  const isOverdue   = s?.payoutDueDate && s.payoutDueDate < today && s.status !== "paid";
                  const isDueToday  = s?.payoutDueDate === today && s?.status !== "paid";
                  const canPay      = s?.status === "ready" || s?.status === "pending";
                  return (
                    <tr key={t.taskId}
                      onMouseEnter={e => (e.currentTarget.style.background = "#f9fafb")}
                      onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
                      <td style={{ ...TD, minWidth: 130 }}>
                        {(t.name || t.email)
                          ? <><div style={{ fontWeight: 600 }}>{t.name || t.email}</div>
                              {t.name && t.email && <div style={{ color: "#9ca3af", fontSize: 11 }}>{t.email}</div>}</>
                          : <span style={{ color: "#d1d5db" }}>정보 없음</span>}
                      </td>
                      <td style={TD}>
                        <span style={{
                          padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 700,
                          background: t.taskStatus === "done" ? "#dcfce7" : t.taskStatus === "working" ? "#dbeafe" : "#f3f4f6",
                          color: t.taskStatus === "done" ? "#15803d" : t.taskStatus === "working" ? "#2563eb" : "#6b7280",
                        }}>
                          {{ waiting: "대기", assigned: "배정", working: "진행", done: "완료" }[t.taskStatus] ?? t.taskStatus}
                        </span>
                      </td>
                      <td style={{ ...TD, whiteSpace: "nowrap" as const }}>
                        {t.deliveryDate
                          ? <div>
                              <div style={{ fontWeight: 500 }}>{fmtMD(t.deliveryDate)}</div>
                              {s?.isAutoGenerated && <div style={{ fontSize: 10, color: "#7c3aed", fontWeight: 600 }}>🤖 자동</div>}
                            </div>
                          : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={{ ...TD, whiteSpace: "nowrap" as const }}>
                        {s?.payoutDueDate ? (
                          <div>
                            <span style={{ fontWeight: 600, color: isOverdue ? "#dc2626" : isDueToday ? "#d97706" : "#111827" }}>
                              {s.payoutDueDate}
                            </span>
                            {isOverdue && <div style={{ marginTop: 2 }}><span style={{ padding: "1px 5px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: "#fee2e2", color: "#dc2626" }}>지연</span></div>}
                            {isDueToday && <div style={{ marginTop: 2 }}><span style={{ padding: "1px 5px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: "#fef3c7", color: "#d97706" }}>오늘</span></div>}
                          </div>
                        ) : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={{ ...TD, fontWeight: 700, color: "#0891b2", whiteSpace: "nowrap" as const }}>
                        {s ? `${Math.round(gross).toLocaleString()}원` : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={{ ...TD, fontSize: 12, color: "#b45309", whiteSpace: "nowrap" as const }}>
                        {withholding > 0
                          ? <><div>{Math.round(withholding).toLocaleString()}원</div><div style={{ fontSize: 10, color: "#9ca3af" }}>3.3%</div></>
                          : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={{ ...TD, fontWeight: 700, color: "#059669", whiteSpace: "nowrap" as const }}>
                        {s ? `${Math.round(net).toLocaleString()}원` : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={TD}>
                        {s?.settlementType
                          ? <span style={{ padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 600, ...(SETTLEMENT_TYPE_STYLE[s.settlementType] ?? { background: "#f3f4f6", color: "#6b7280" }) }}>
                              {SETTLEMENT_TYPE_KO[s.settlementType] ?? s.settlementType}
                            </span>
                          : <span style={{ color: "#d1d5db" }}>—</span>}
                      </td>
                      <td style={TD}>
                        {s ? (
                          <div>
                            <span style={{ padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 700, ...(SETTLE_STATUS_BADGE[s.status] ?? {}) }}>
                              {SETTLE_STATUS_KO[s.status] ?? s.status}
                            </span>
                            {s.reviewReason && (
                              <div style={{ fontSize: 10, color: "#b45309", marginTop: 3, maxWidth: 120 }} title={s.reviewReason}>
                                {s.reviewReason.slice(0, 25)}{s.reviewReason.length > 25 ? "…" : ""}
                              </div>
                            )}
                            {s.paidAt && <div style={{ fontSize: 10, color: "#9ca3af", marginTop: 2 }}>지급일: {fmtDate(s.paidAt)}</div>}
                          </div>
                        ) : <span style={{ padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 600, background: "#f1f5f9", color: "#94a3b8" }}>정산 없음</span>}
                      </td>
                      {/* 액션 열 */}
                      <td style={{ ...TD, width: 90 }}>
                        {s && canPay && (
                          <button onClick={() => handlePay(s.id)} disabled={payingId === s.id}
                            style={{ padding: "5px 10px", borderRadius: 6, fontSize: 11, fontWeight: 700, cursor: "pointer", border: "none", background: payingId === s.id ? "#e5e7eb" : "#059669", color: payingId === s.id ? "#6b7280" : "#fff" }}>
                            {payingId === s.id ? "처리 중…" : "💸 지급"}
                          </button>
                        )}
                        {s?.status === "paid" && <span style={{ fontSize: 11, color: "#15803d", fontWeight: 600 }}>✓ 완료</span>}
                        {!s && <span style={{ fontSize: 11, color: "#d1d5db" }}>—</span>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
              {translators.some(t => t.settlement) && (
                <tfoot>
                  <tr style={{ background: "#f9fafb", borderTop: "2px solid #e5e7eb" }}>
                    <td colSpan={4} style={{ ...TD, fontWeight: 700 }}>합계</td>
                    <td style={{ ...TD, fontWeight: 700, color: "#0891b2", whiteSpace: "nowrap" as const }}>
                      {translators.reduce((s, t) => s + Number(t.settlement?.grossAmount ?? 0), 0).toLocaleString()}원
                    </td>
                    <td style={{ ...TD, fontWeight: 700, color: "#b45309", whiteSpace: "nowrap" as const }}>
                      {translators.reduce((s, t) => s + Number(t.settlement?.withholdingAmount ?? 0), 0).toLocaleString()}원
                    </td>
                    <td style={{ ...TD, fontWeight: 800, color: "#059669", whiteSpace: "nowrap" as const }}>
                      {translators.reduce((s, t) => s + Number(t.settlement?.netAmount ?? 0), 0).toLocaleString()}원
                    </td>
                    <td colSpan={3} style={TD} />
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        )}
      </div>

      {/* ── 결제/지급 하단 2분할 ──────────────────────────────────────────────── */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>

        {/* 고객 결제 현황 */}
        <div style={card}>
          <div style={{ ...sectionHd, marginBottom: 12 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <span>💳 고객 결제 현황</span>
              <span style={{
                padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 700,
                background: payBadge.bg, color: payBadge.color,
              }}>{payBadge.label}</span>
            </div>
            {/* 버튼: 미완료일 때만 표시 */}
            {!isFullyPaid && (
              <button onClick={onOpenPaymentForm}
                style={{ padding: "5px 12px", borderRadius: 7, fontSize: 11, fontWeight: 700,
                  cursor: "pointer", border: "none",
                  background: !hasPayments ? "#059669" : "#f9fafb",
                  color: !hasPayments ? "#fff" : "#374151",
                  ...(hasPayments ? { border: "1px solid #e5e7eb" } : {}),
                } as React.CSSProperties}>
                {hasPayments ? "✏️ 수정 등록" : "＋ 결제 등록"}
              </button>
            )}
          </div>

          {!hasPayments ? (
            <EmptyCTA icon="💳" text="결제 내역이 없습니다." btnLabel="결제 등록하기" onClick={onOpenPaymentForm} />
          ) : (
            <>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr>{["결제일","금액","방법","상태"].map(h => <th key={h} style={TH}>{h}</th>)}</tr>
                </thead>
                <tbody>
                  {payments.map(p => (
                    <tr key={p.id}>
                      <td style={{ ...TD, whiteSpace: "nowrap" as const }}>{fmtDate(p.createdAt)}</td>
                      <td style={{ ...TD, fontWeight: 700, color: p.status === "paid" ? "#059669" : "#374151" }}>
                        {Number(p.amount).toLocaleString()}원
                      </td>
                      <td style={{ ...TD, color: "#6b7280" }}>{p.paymentMethod ?? "—"}</td>
                      <td style={TD}><StatusBadge status={p.status} /></td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr style={{ background: "#f9fafb", borderTop: "1px solid #e5e7eb" }}>
                    <td style={{ ...TD, fontWeight: 700 }}>입금 합계</td>
                    <td style={{ ...TD, fontWeight: 800, color: "#059669" }}>{summary.paidAmount.toLocaleString()}원</td>
                    <td colSpan={2} style={TD} />
                  </tr>
                  {summary.unpaidAmount > 0 && (
                    <tr style={{ background: "#fff7f7" }}>
                      <td style={{ ...TD, fontWeight: 700, color: "#dc2626" }}>미수금</td>
                      <td style={{ ...TD, fontWeight: 800, color: "#dc2626" }}>{summary.unpaidAmount.toLocaleString()}원</td>
                      <td colSpan={2} style={TD} />
                    </tr>
                  )}
                </tfoot>
              </table>
              {/* 결제 완료 상태 */}
              {isFullyPaid && (
                <div style={{ marginTop: 10, padding: "8px 12px", background: "#f0fdf4", borderRadius: 8, border: "1px solid #bbf7d0", fontSize: 12, fontWeight: 600, color: "#15803d" }}>
                  ✅ 결제가 완료되었습니다.
                </div>
              )}
            </>
          )}
        </div>

        {/* 통번역사 지급 현황 */}
        <div style={card}>
          <div style={{ ...sectionHd, marginBottom: 12 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <span>💸 통번역사 지급 현황</span>
              <span style={{
                padding: "2px 8px", borderRadius: 6, fontSize: 11, fontWeight: 700,
                background: settleBadge.bg, color: settleBadge.color,
              }}>{settleBadge.label}</span>
            </div>
          </div>

          {!hasSettlements ? (
            <div style={{ textAlign: "center", padding: "20px 16px", background: "#f9fafb", borderRadius: 8, border: "1px dashed #d1d5db" }}>
              <div style={{ fontSize: 28, marginBottom: 8 }}>📄</div>
              <p style={{ margin: "0 0 4px", fontSize: 13, color: "#6b7280" }}>정산이 아직 생성되지 않았습니다.</p>
              <p style={{ margin: 0, fontSize: 11, color: "#c0c8d4" }}>프로젝트 완료 시 자동 생성되거나 정산 탭에서 수동 생성 가능합니다.</p>
            </div>
          ) : (
            <>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr>{["번역사","지급예정일","실지급액","상태","액션"].map(h => <th key={h} style={TH}>{h}</th>)}</tr>
                </thead>
                <tbody>
                  {translators.filter(t => t.settlement).map(t => {
                    const s = t.settlement!;
                    const isOverdue = s.payoutDueDate && s.payoutDueDate < today && s.status !== "paid";
                    const canPay    = s.status === "ready" || s.status === "pending";
                    return (
                      <tr key={t.taskId}>
                        <td style={{ ...TD, fontWeight: 600 }}>{t.name || t.email || "—"}</td>
                        <td style={{ ...TD, whiteSpace: "nowrap" as const }}>
                          <span style={{ fontWeight: 600, color: isOverdue ? "#dc2626" : "#111827" }}>
                            {s.payoutDueDate ?? "—"}
                          </span>
                          {isOverdue && <span style={{ marginLeft: 4, padding: "1px 4px", borderRadius: 4, fontSize: 10, fontWeight: 700, background: "#fee2e2", color: "#dc2626" }}>지연</span>}
                        </td>
                        <td style={{ ...TD, fontWeight: 700, color: "#059669" }}>
                          {Number(s.netAmount ?? 0).toLocaleString()}원
                        </td>
                        <td style={TD}>
                          <span style={{ padding: "2px 7px", borderRadius: 6, fontSize: 11, fontWeight: 700, ...(SETTLE_STATUS_BADGE[s.status] ?? {}) }}>
                            {SETTLE_STATUS_KO[s.status] ?? s.status}
                          </span>
                          {s.paidAt && <div style={{ fontSize: 10, color: "#9ca3af", marginTop: 1 }}>지급일: {fmtDate(s.paidAt)}</div>}
                        </td>
                        <td style={TD}>
                          {canPay && (
                            <button onClick={() => handlePay(s.id)} disabled={payingId === s.id}
                              style={{ padding: "5px 10px", borderRadius: 6, fontSize: 11, fontWeight: 700, cursor: "pointer", border: "none", background: payingId === s.id ? "#e5e7eb" : "#059669", color: payingId === s.id ? "#6b7280" : "#fff" }}>
                              {payingId === s.id ? "처리 중…" : "지급"}
                            </button>
                          )}
                          {s.status === "paid" && <span style={{ fontSize: 11, color: "#15803d", fontWeight: 600 }}>✓ 완료</span>}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr style={{ background: "#f9fafb", borderTop: "1px solid #e5e7eb" }}>
                    <td style={{ ...TD, fontWeight: 700 }}>지급 합계</td>
                    <td style={TD} />
                    <td style={{ ...TD, fontWeight: 800, color: "#059669" }}>
                      {summary.totalPayoutAmount.toLocaleString()}원
                    </td>
                    <td colSpan={2} style={TD} />
                  </tr>
                </tfoot>
              </table>

              {/* 지급 가능한 경우 강조 CTA */}
              {hasPayableSettlement && !allSettlementsPaid && (
                <div style={{ marginTop: 10, padding: "12px 14px", background: "#f0fdf4", borderRadius: 8, border: "1.5px solid #86efac", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 }}>
                  <span style={{ fontSize: 12, fontWeight: 600, color: "#15803d" }}>
                    💸 지급 처리가 가능한 정산이 있습니다.
                  </span>
                  <button
                    onClick={() => {
                      const first = translators.find(t => t.settlement?.status === "ready" || t.settlement?.status === "pending");
                      if (first?.settlement) handlePay(first.settlement.id);
                    }}
                    disabled={payingId !== null}
                    style={primaryBtn({ background: "#059669", fontSize: 12, opacity: payingId !== null ? 0.6 : 1 })}>
                    지급 처리하기
                  </button>
                </div>
              )}

              {/* 지급 완료 상태 */}
              {allSettlementsPaid && (
                <div style={{ marginTop: 10, padding: "8px 12px", background: "#f0fdf4", borderRadius: 8, border: "1px solid #bbf7d0", fontSize: 12, fontWeight: 600, color: "#15803d" }}>
                  ✅ 모든 정산이 지급 완료되었습니다.
                </div>
              )}
            </>
          )}
        </div>
      </div>

      {/* ── 돈 흐름 요약 ────────────────────────────────────────────────────────── */}
      <div style={{ ...card, background: "#f8faff", borderColor: "#bfdbfe" }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: "#111827", marginBottom: 12 }}>💡 프로젝트 돈 흐름</div>
        <div style={{ display: "flex", alignItems: "center", gap: 0, flexWrap: "wrap" }}>
          <FlowPill
            color="#3b82f6" label="판매금액"
            value={hasQuotes ? fmtWon(summary.saleTotalAmount) : "미등록"}
            dimmed={!hasQuotes}
          />
          <FlowArrow />
          <FlowPill
            color={summary.paymentStatus === "fully_paid" ? "#059669" : summary.paymentStatus === "partial" ? "#d97706" : "#dc2626"}
            label={`고객 입금${isFullyPaid ? " ✓" : ""}`}
            value={fmtWon(summary.paidAmount)}
            sub={summary.unpaidAmount > 0 ? `미수 ${fmtWon(summary.unpaidAmount)}` : undefined}
          />
          <FlowArrow />
          <FlowPill
            color={allSettlementsPaid ? "#059669" : summary.settlementStatus === "pending_review" ? "#d97706" : "#8b5cf6"}
            label={`번역사 지급${allSettlementsPaid ? " ✓" : ""}`}
            value={hasSettlements ? fmtWon(summary.totalPayoutAmount) : "없음"}
            dimmed={!hasSettlements}
          />
          <FlowArrow />
          <FlowPill
            color={!hasQuotes ? "#d1d5db" : summary.estimatedMargin >= 0 ? "#059669" : "#dc2626"}
            label="예상 차액"
            value={!hasQuotes ? "—" : (summary.estimatedMargin >= 0 ? "+" : "") + fmtWon(summary.estimatedMargin)}
            sub={hasQuotes && summary.saleTotalAmount > 0
              ? `마진율 ${Math.round((summary.estimatedMargin / summary.saleTotalAmount) * 100)}%`
              : undefined}
            dimmed={!hasQuotes}
          />
        </div>
      </div>

    </div>
  );
}

// ── 서브 컴포넌트 ─────────────────────────────────────────────────────────────

function SCard({ topColor, label, main, mainColor, sub, badge }: {
  topColor: string; label: string;
  main?: string; mainColor?: string; sub?: string;
  badge?: { label: string; bg: string; color: string };
}) {
  return (
    <div style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 12, padding: "14px 18px", position: "relative", overflow: "hidden" }}>
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: topColor }} />
      <p style={{ margin: "0 0 4px", fontSize: 10, fontWeight: 700, color: topColor, textTransform: "uppercase", letterSpacing: "0.05em" }}>{label}</p>
      {badge ? (
        <span style={{ display: "inline-block", padding: "3px 10px", borderRadius: 8, fontSize: 12, fontWeight: 700, background: badge.bg, color: badge.color, marginBottom: 2 }}>
          {badge.label}
        </span>
      ) : (
        <p style={{ margin: "0 0 2px", fontSize: 18, fontWeight: 800, color: mainColor ?? "#111827" }}>{main}</p>
      )}
      {sub && <p style={{ margin: 0, fontSize: 10, color: "#9ca3af" }}>{sub}</p>}
    </div>
  );
}

function FlowPill({ color, label, value, sub, dimmed }: {
  color: string; label: string; value: string; sub?: string; dimmed?: boolean;
}) {
  return (
    <div style={{
      background: "#fff", border: `1.5px solid ${dimmed ? "#e5e7eb" : color}`,
      borderRadius: 10, padding: "8px 14px", minWidth: 110,
      textAlign: "center" as const, opacity: dimmed ? 0.55 : 1,
    }}>
      <div style={{ fontSize: 10, fontWeight: 700, color: dimmed ? "#9ca3af" : color, marginBottom: 2, textTransform: "uppercase" as const }}>{label}</div>
      <div style={{ fontSize: 14, fontWeight: 800, color: dimmed ? "#9ca3af" : "#111827" }}>{value}</div>
      {sub && <div style={{ fontSize: 10, color: "#9ca3af", marginTop: 1 }}>{sub}</div>}
    </div>
  );
}

function FlowArrow() {
  return <div style={{ fontSize: 18, color: "#9ca3af", margin: "0 6px" }}>→</div>;
}
