import {
  pgTable, serial, integer, numeric, timestamp, text, boolean,
  pgEnum, date, jsonb,
} from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { usersTable } from "./users";
import { paymentsTable } from "./payments";
import { tasksTable } from "./tasks";

// 정산 상태: draft(정보부족), pending_review(검토필요), ready(지급준비), paid(지급완료)
export const settlementStatusEnum = pgEnum("settlement_status", [
  "draft",
  "pending_review",
  "pending",
  "ready",
  "paid",
]);

// 정산 유형
export const settlementTypeEnum = pgEnum("settlement_type", [
  "WITHHOLDING_3_3",
  "VAT_INVOICE",
  "OVERSEAS_REMITTANCE",
  "OTHER_REVIEW",
]);

export const settlementsTable = pgTable("settlements", {
  id: serial("id").primaryKey(),

  // ── 연결 정보 ─────────────────────────────────────────────────────────────
  projectId: integer("project_id")
    .notNull()
    .references(() => projectsTable.id),
  taskId: integer("task_id")
    .references(() => tasksTable.id),
  translatorId: integer("translator_id")
    .notNull()
    .references(() => usersTable.id),
  paymentId: integer("payment_id")
    .references(() => paymentsTable.id),

  // ── 스냅샷 (생성 시점 정보 고정) ──────────────────────────────────────────
  translatorName: text("translator_name"),
  bankInfoSnapshot: jsonb("bank_info_snapshot"),

  // ── 금액 (기존 호환 유지 + 신규 필드) ────────────────────────────────────
  totalAmount: numeric("total_amount", { precision: 12, scale: 2 }).notNull(),
  translatorAmount: numeric("translator_amount", { precision: 12, scale: 2 }).notNull(),
  platformFee: numeric("platform_fee", { precision: 12, scale: 2 }).notNull(),

  // 원금액 (고객 결제 금액)
  grossAmount: numeric("gross_amount", { precision: 12, scale: 2 }),
  // 실지급액 (세금 공제 후)
  netAmount: numeric("net_amount", { precision: 12, scale: 2 }),

  // ── 세금 계산 ─────────────────────────────────────────────────────────────
  settlementType: settlementTypeEnum("settlement_type"),
  withholdingRate: numeric("withholding_rate", { precision: 7, scale: 4 }),
  withholdingAmount: numeric("withholding_amount", { precision: 12, scale: 2 }),
  vatAmount: numeric("vat_amount", { precision: 12, scale: 2 }),

  // ── 지급 정보 ─────────────────────────────────────────────────────────────
  paymentMethod: text("payment_method"),
  payoutDueDate: date("payout_due_date"),

  // ── 상태 및 검토 ──────────────────────────────────────────────────────────
  status: settlementStatusEnum("status").notNull().default("pending"),
  reviewReason: text("review_reason"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),

  // ── 지급 처리 ─────────────────────────────────────────────────────────────
  paidDate: timestamp("paid_date"),
  paidAt: timestamp("paid_at"),
  paymentMemo: text("payment_memo"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type Settlement = typeof settlementsTable.$inferSelect;
export type InsertSettlement = typeof settlementsTable.$inferInsert;
