export const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");
export const api = (path: string) => `${BASE}${path}`;

export const TOKEN_KEY = "auth_token";
export const USER_KEY = "auth_user";
export const PERM_KEY = "auth_permissions";

export type Role = "admin" | "staff" | "client" | "linguist" | "customer" | "translator";
export type User = {
  id: number;
  email: string;
  role: Role;
  name?: string | null;
  roleId?: number | null;
  permissions?: string[];
};
export type NavPage = "dashboard" | "admin";

export type Project = {
  id: number; userId: number; title: string;
  fileUrl: string | null; status: string; createdAt: string;
};
export type Task = {
  id: number; projectId: number; translatorId: number;
  status: string; createdAt: string;
  projectTitle: string | null; projectStatus: string | null;
};
export type PaymentPanel = { projectId: number; paymentId: number; amount: number } | null;
export type AdminSettlement = {
  id: number; projectId: number; taskId: number | null; translatorId: number; paymentId: number | null;
  translatorName: string | null;
  totalAmount: string; translatorAmount: string; platformFee: string;
  grossAmount: string | null; netAmount: string | null;
  settlementType: string | null;
  withholdingRate: string | null; withholdingAmount: string | null; vatAmount: string | null;
  paymentMethod: string | null; payoutDueDate: string | null;
  status: string; reviewReason: string | null; isAutoGenerated: boolean;
  createdAt: string;
  paidDate: string | null; paidAt: string | null; paymentMemo: string | null;
  projectTitle: string | null; translatorEmail: string | null;
  companyName: string | null;
};
export type MySettlement = {
  id: number; projectId: number;
  totalAmount: string; translatorAmount: string; platformFee: string;
  status: string; createdAt: string; projectTitle: string | null;
};
export type AdminProject = {
  id: number; title: string; status: string; fileUrl: string | null;
  createdAt: string; customerEmail: string | null; customerId: number | null;
  projectCustomerId: number | null; adminId: number | null;
  contactId: number | null; companyId: number | null;
  contactName: string | null; companyName: string | null;
  financialStatus?: string | null;
  divisionName?: string | null;
  billingCompanyName?: string | null;
  payerCompanyName?: string | null;
  requestingCompanyName?: string | null;
  requestingCompanyId?: number | null;
  requestingDivisionId?: number | null;
  billingCompanyId?: number | null;
  payerCompanyId?: number | null;
};
export type AdminPayment = {
  id: number; projectId: number; amount: number; status: string;
  createdAt: string; projectTitle: string | null; projectStatus: string | null;
};
export type AdminTask = {
  id: number; projectId: number; translatorId: number; status: string;
  createdAt: string; projectTitle: string | null; projectStatus: string | null;
  translatorEmail: string | null;
};
export type LogEntry = { id: number; entityType: string; entityId: number; action: string; performedByEmail: string | null; metadata: string | null; createdAt: string };
export type NoteEntry = { id: number; content: string; createdAt: string; adminEmail: string | null };
export type AdminUser = {
  id: number; email: string; role: Role; isActive: boolean; createdAt: string;
  name?: string; roleId?: number | null;
  department?: string | null; jobTitle?: string | null; companyId?: number | null;
  lastLoginAt?: string | null; lastActivityAt?: string | null; isOnline?: boolean;
};
export type AdminCustomer = {
  id: number; companyName: string; contactName: string; email: string;
  phone: string | null; createdAt: string;
  projectCount: number; totalPayment: number;
  unpaidAmount: number; lastTransactionAt: string | null; inProgressCount: number;
};
export type CustomerProjectItem = { id: number; title: string; status: string; createdAt: string };
export type CustomerDetail = AdminCustomer & {
  projects: CustomerProjectItem[];
  totalSettlement: number;
};
export type Communication = {
  id: number; customerId: number; projectId: number | null;
  type: "email" | "phone" | "message"; content: string; createdAt: string;
  companyName?: string | null; contactName?: string | null;
};
export type ProjectTaskDetail = {
  id: number; translatorId: number; status: string; createdAt: string;
  translatorEmail: string | null;
  translatorProfile: {
    languagePairs: string | null; specializations: string | null;
    rating: number | null; availabilityStatus: string; bio: string | null;
  } | null;
  translatorRates: TranslatorRate[];
};
export type MatchCandidate = {
  id: number; email: string; name: string | null; score: number;
  profile: {
    languagePairs: string | null; specializations: string | null;
    rating: number | null; availabilityStatus: string; bio: string | null;
    phone: string | null; region: string | null; grade: string | null;
    education: string | null; major: string | null; graduationYear: number | null;
  } | null;
  rates: TranslatorRate[];
};
export type ProjectDetail = AdminProject & {
  quotes: Array<{ id: number; price: string | number; amount?: number; status: string; createdAt: string }>;
  payments: Array<{ id: number; amount: number; status: string; createdAt: string }>;
  tasks: ProjectTaskDetail[];
  settlements: Array<{ id: number; totalAmount: number; translatorAmount: number; platformFee: number; status: string; createdAt: string }>;
  logs: LogEntry[];
  notes: NoteEntry[];
  communications: Communication[];
  company: { id: number; name: string; representativeName: string | null; email: string | null; phone: string | null; industry: string | null } | null;
  contact: { id: number; name: string; department: string | null; position: string | null; email: string | null; phone: string | null } | null;
};
export type CompanyType = "client" | "vendor";
export type VendorType = "interpretation_equipment" | "editing" | "translation_agency" | "cleaning" | "water_supply" | "etc" | string;
export const VENDOR_TYPE_LABELS: Record<string, string> = {
  interpretation_equipment: "통역장비",
  editing: "편집/감수",
  translation_agency: "통번역업체",
  cleaning: "청소",
  water_supply: "생수",
  etc: "기타",
};
export const VENDOR_TYPE_OPTIONS = [
  { value: "interpretation_equipment", label: "통역장비" },
  { value: "editing",                  label: "편집/감수" },
  { value: "translation_agency",       label: "통번역업체" },
  { value: "cleaning",                 label: "청소" },
  { value: "water_supply",             label: "생수" },
  { value: "etc",                      label: "기타" },
];
export type Company = {
  id: number; name: string; businessNumber: string | null; industry: string | null;
  address: string | null; website: string | null; notes: string | null;
  representativeName: string | null; email: string | null; phone: string | null; mobile: string | null;
  createdAt: string; contactCount: number; projectCount: number; totalPayment: number;
  companyType: CompanyType; vendorType: VendorType | null;
  /** 소속 브랜드/부서명 목록 */
  divisionNames?: string[];
  /** 검색어와 매칭된 브랜드/부서명 (검색 시만 존재) */
  matchedDivisionName?: string | null;
};
export type Division = {
  id: number; companyId: number; name: string; type: string | null; createdAt: string;
  projectCount?: number; totalPayment?: number; contactCount?: number;
};
export type Contact = {
  id: number; companyId: number; divisionId: number | null; name: string;
  department: string | null; position: string | null;
  email: string | null; phone: string | null; mobile: string | null; officePhone: string | null;
  notes: string | null; memo: string | null;
  isPrimary: boolean; isQuoteContact: boolean; isBillingContact: boolean; isActive: boolean;
  createdAt: string; updatedAt: string;
};
export type AdminContact = {
  id: number; companyId: number; companyName: string | null; divisionId: number | null; divisionName: string | null;
  name: string; department: string | null; position: string | null;
  email: string | null; phone: string | null; mobile: string | null; officePhone: string | null;
  notes: string | null; memo: string | null;
  isPrimary: boolean; isQuoteContact: boolean; isBillingContact: boolean; isActive: boolean;
  createdAt: string; updatedAt: string;
};
export type TranslatorRate = {
  id: number; translatorId: number; serviceType: string; subType: string | null;
  language: string | null; languagePair: string | null; unit: string; rate: number;
  currency: string; vatIncluded: boolean;
  minPrice: number | null; baseHours: number | null; overtimeRate: number | null;
  isDefault: boolean; isActive: boolean;
  memo: string | null; createdAt: string;
};
export type TranslatorListItem = {
  id: number; email: string; name: string | null; isActive: boolean; createdAt: string;
  profileId: number | null; languagePairs: string | null; languageLevel: string | null;
  specializations: string | null; phone: string | null;
  region: string | null; grade: string | null;
  rating: number | null; availabilityStatus: string | null;
  bio: string | null;
  resumeUrl: string | null; portfolioUrl: string | null;
  education: string | null; major: string | null;
  workTypes: string[]; subTypes: string[];
  residentNumber: string | null;
};
export type ContactDetail = {
  id: number; companyId: number; companyName: string | null; divisionId: number | null; divisionName: string | null;
  name: string; department: string | null; position: string | null;
  email: string | null; phone: string | null; mobile: string | null;
  officePhone: string | null; notes: string | null; memo: string | null; createdAt: string;
  isPrimary: boolean; isQuoteContact: boolean; isBillingContact: boolean; isActive: boolean;
  projects: Array<{ id: number; title: string; status: string; createdAt: string }>;
  communications: Array<{ id: number; type: string; content: string; projectId: number | null; createdAt: string }>;
};
export type CompanyDetail = Company & {
  contacts: Contact[];
  divisions: Division[];
  projects: Array<{ id: number; title: string; status: string; createdAt: string; requestingDivisionId?: number | null }>;
  totalQuote: number;
  totalPayment: number;
  totalSettlement: number;
  prepaidBalance: number | null;
  activeAccumulatedCount: number;
  unpaidAmount: number;
  lastProjectDate: string | null;
  lastPaymentDate: string | null;
  nameHistory?: Array<{
    id: number; companyId: number; companyName: string; nameType: string;
    validFrom: string | null; validTo: string | null; reason: string | null;
    changedByEmail: string | null; changedAt: string;
  }>;
};
export type ProductOption = {
  id: number; productId: number; optionType: string; optionValue: string; sortOrder: number | null;
};
export type Product = {
  id: number; code: string; name: string;
  productType: string;
  sourceLanguage: string | null; targetLanguage: string | null;
  languagePair: string | null;
  mainCategory: string | null; subCategory: string | null;
  category: string | null; field: string | null;
  unit: string; basePrice: number; description: string | null;
  active: boolean; createdAt: string;
  options: ProductOption[];
  interpretationDuration: string | null; overtimePrice: number | null;
  deactivationReason: string | null;
  quantityUnit: string | null;
  usagePeriod: string | null;
  interpretationDirection: string | null;
};
export type BoardPost = {
  id: number; category: string; title: string; content?: string;
  pinned: boolean; visibleToAll: boolean;
  createdAt: string; updatedAt: string;
  authorId: number; authorEmail: string | null;
};
export type TranslatorProfile = {
  id?: number; userId: number;
  phone?: string | null;
  languagePairs?: string | null; languageLevel?: string | null;
  specializations?: string | null;
  education?: string | null; major?: string | null;
  graduationYear?: number | null; region?: string | null;
  grade?: string | null;
  rating?: number | null; availabilityStatus?: string;
  bio?: string | null; ratePerWord?: number | null; ratePerPage?: number | null;
  unitType?: string | null; unitPrice?: number | null;
  resumeUrl?: string | null; portfolioUrl?: string | null;
};

export type TranslatorProduct = {
  id: number; translatorId: number; productId: number;
  productName: string | null; productCode: string | null;
  mainCategory: string | null; subCategory: string | null;
  productUnit: string | null; productBasePrice: number | null;
  unitPrice: number | null; note: string | null;
  createdAt: string;
};

export function saveSession(token: string, user: User, permissions?: string[]) {
  localStorage.setItem(TOKEN_KEY, token);
  localStorage.setItem(USER_KEY, JSON.stringify(user));
  if (permissions) localStorage.setItem(PERM_KEY, JSON.stringify(permissions));
}
export function clearSession() {
  localStorage.removeItem(TOKEN_KEY);
  localStorage.removeItem(USER_KEY);
  localStorage.removeItem(PERM_KEY);
}
export function loadSession(): { token: string; user: User; permissions: string[] } | null {
  const token = localStorage.getItem(TOKEN_KEY);
  const raw = localStorage.getItem(USER_KEY);
  if (!token || !raw) return null;
  try {
    const user = JSON.parse(raw) as User;
    const rawPerms = localStorage.getItem(PERM_KEY);
    const permissions: string[] = rawPerms ? JSON.parse(rawPerms) : (user.permissions ?? []);
    return { token, user, permissions };
  } catch { return null; }
}
export function getDefaultPage(role: Role): NavPage {
  return (role === "admin" || role === "staff") ? "admin" : "dashboard";
}

export const STATUS_LABEL: Record<string, string> = {
  created: "접수됨", quoted: "견적 발송", approved: "견적 승인",
  paid: "결제 완료", matched: "통번역사 배정", in_progress: "진행 중",
  completed: "완료", cancelled: "취소됨", waiting: "대기", assigned: "배정됨",
  working: "작업 중", done: "완료",
  pending: "대기", ready: "지급 준비",
  draft: "정보 부족", pending_review: "검토 필요",
};
export const FINANCIAL_STATUS_LABEL: Record<string, string> = {
  unbilled:   "미청구",
  billed:     "청구 완료",
  receivable: "미수금",
  paid:       "입금 완료",
};
export const FINANCIAL_STATUS_STYLE: Record<string, React.CSSProperties> = {
  unbilled:   { background: "#f3f4f6", color: "#6b7280" },
  billed:     { background: "#eff6ff", color: "#2563eb" },
  receivable: { background: "#fef3c7", color: "#b45309" },
  paid:       { background: "#f0fdf4", color: "#15803d" },
};
export const STATUS_STYLE: Record<string, React.CSSProperties> = {
  created:     { background: "#f3f4f6", color: "#6b7280" },
  quoted:      { background: "#eff6ff", color: "#2563eb" },
  approved:    { background: "#f0fdf4", color: "#16a34a" },
  paid:        { background: "#ecfeff", color: "#0891b2" },
  matched:     { background: "#faf5ff", color: "#9333ea" },
  in_progress: { background: "#fffbeb", color: "#d97706" },
  completed:   { background: "#f0fdf4", color: "#059669" },
  cancelled:   { background: "#fef2f2", color: "#dc2626" },
  waiting:     { background: "#f3f4f6", color: "#6b7280" },
  assigned:    { background: "#eff6ff", color: "#2563eb" },
  working:     { background: "#fffbeb", color: "#d97706" },
  done:        { background: "#f0fdf4", color: "#059669" },
  pending:        { background: "#f3f4f6", color: "#6b7280" },
  ready:          { background: "#ecfdf5", color: "#059669" },
  draft:          { background: "#f3f4f6", color: "#6b7280" },
  pending_review: { background: "#fef3c7", color: "#b45309" },
  failed:         { background: "#fef2f2", color: "#dc2626" },
};
export const ROLE_STYLE: Record<Role, React.CSSProperties> = {
  admin:      { background: "#fef2f2", color: "#dc2626" },
  staff:      { background: "#fff7ed", color: "#ea580c" },
  client:     { background: "#eff6ff", color: "#2563eb" },
  linguist:   { background: "#faf5ff", color: "#7c3aed" },
  customer:   { background: "#eff6ff", color: "#2563eb" },
  translator: { background: "#faf5ff", color: "#7c3aed" },
};
export const ROLE_LABEL: Record<Role, string> = {
  admin:      "관리자",
  staff:      "직원",
  client:     "고객",
  linguist:   "통번역사",
  customer:   "고객",
  translator: "통번역사",
};
export const BOARD_CATEGORY_LABEL: Record<string, string> = { notice: "공지", reference: "통역자료", manual: "내부매뉴얼" };
export const AVAILABILITY_LABEL: Record<string, string> = { available: "가능", busy: "바쁨", unavailable: "불가" };
export const ALL_PROJECT_STATUSES = ["created","quoted","approved","matched","in_progress","completed","cancelled"] as const;
export const ALL_FINANCIAL_STATUSES = ["unbilled","billed","receivable","paid"] as const;
export const ALL_PAYMENT_STATUSES = ["pending","paid","failed"] as const;
export const ALL_SETTLEMENT_STATUSES = ["pending_review", "ready", "pending", "draft", "paid"] as const;
export const PROJECT_STATUS_TRANSITIONS: Record<string, string[]> = {
  created:     ["quoted", "cancelled"],
  quoted:      ["created", "approved", "cancelled"],
  approved:    ["quoted", "matched", "cancelled"],
  matched:     ["in_progress", "approved", "quoted", "cancelled"],
  in_progress: ["matched", "completed", "cancelled"],
  completed:   ["in_progress"],
  cancelled:   ["created"],
};
export const ACTION_LABEL: Record<string, { ko: string; color: string; dot: string }> = {
  project_created:                  { ko: "프로젝트 접수",         color: "#2563eb", dot: "🗂️" },
  quote_created:                    { ko: "견적 생성",              color: "#7c3aed", dot: "📋" },
  quote_updated:                    { ko: "견적 수정",              color: "#7c3aed", dot: "📝" },
  quote_approved:                   { ko: "견적 승인",              color: "#16a34a", dot: "✅" },
  payment_requested:                { ko: "결제 요청",              color: "#d97706", dot: "💳" },
  payment_paid:                     { ko: "결제 완료",              color: "#0891b2", dot: "💰" },
  payment_failed:                   { ko: "결제 실패",              color: "#dc2626", dot: "❌" },
  payment_received:                 { ko: "결제 확인",              color: "#059669", dot: "💰" },
  project_matched:                  { ko: "통번역사 매칭",            color: "#9333ea", dot: "🔗" },
  task_assigned:                    { ko: "통번역사 배정",            color: "#9333ea", dot: "👤" },
  task_started:                     { ko: "작업 시작",              color: "#d97706", dot: "▶️" },
  task_completed:                   { ko: "작업 완료",              color: "#059669", dot: "🎉" },
  settlement_created:               { ko: "정산 생성",              color: "#7c3aed", dot: "📊" },
  settlement_paid:                  { ko: "정산 완료",              color: "#059669", dot: "💸" },
  project_cancelled:                { ko: "프로젝트 취소",          color: "#dc2626", dot: "🚫" },
  admin_project_cancelled:          { ko: "관리자 취소",             color: "#dc2626", dot: "🚫" },
  admin_info_updated:               { ko: "기본정보 수정",           color: "#6b7280", dot: "✏️" },
  admin_rematch:                    { ko: "통번역사 재매칭",           color: "#9333ea", dot: "🔄" },
  note_added:                       { ko: "메모 추가",               color: "#92400e", dot: "📝" },
  file_uploaded_source:             { ko: "원본 파일 업로드",        color: "#0369a1", dot: "📁" },
  file_uploaded_translated:         { ko: "번역본 파일 업로드",      color: "#15803d", dot: "📁" },
  file_uploaded_attachment:         { ko: "첨부 파일 업로드",        color: "#6b7280", dot: "📎" },
  file_deleted:                     { ko: "파일 삭제",               color: "#dc2626", dot: "🗑️" },
  communication_added_email:        { ko: "이메일 커뮤니케이션 기록", color: "#2563eb", dot: "📧" },
  communication_added_phone:        { ko: "전화 커뮤니케이션 기록",  color: "#059669", dot: "📞" },
  communication_added_message:      { ko: "메시지 커뮤니케이션 기록", color: "#7c3aed", dot: "💬" },
};
export function getActionLabel(action: string): { ko: string; color: string; dot: string } {
  if (ACTION_LABEL[action]) return ACTION_LABEL[action];
  if (action.startsWith("admin_forced_status_to_")) {
    const s = action.replace("admin_forced_status_to_", "");
    return { ko: `관리자 강제변경 → ${STATUS_LABEL[s] ?? s}`, color: "#dc2626", dot: "⚡" };
  }
  if (action.startsWith("admin_status_changed_to_")) {
    const s = action.replace("admin_status_changed_to_", "");
    return { ko: `관리자 상태변경 → ${STATUS_LABEL[s] ?? s}`, color: "#6b7280", dot: "🔄" };
  }
  if (action.startsWith("admin_assigned_translator_")) {
    return { ko: "통번역사 직접 배정", color: "#9333ea", dot: "👤" };
  }
  if (action.startsWith("담당자 ")) {
    return { ko: action, color: "#6b7280", dot: "👤" };
  }
  return { ko: action, color: "#6b7280", dot: "•" };
}
export const COMM_TYPE_LABEL: Record<string, string> = { email: "이메일", phone: "전화", message: "메시지" };
export const COMM_TYPE_COLOR: Record<string, string> = { email: "#2563eb", phone: "#059669", message: "#7c3aed" };
export const PROJECT_STEPS = [
  { key: "created", label: "접수" },
  { key: "quoted", label: "견적" },
  { key: "approved", label: "승인" },
  { key: "paid", label: "결제" },
  { key: "matched", label: "통번역사 배정" },
  { key: "in_progress", label: "번역 중" },
  { key: "completed", label: "완료" },
] as const;
export const PROJECT_STEP_KEYS = PROJECT_STEPS.map(s => s.key);
export const FEEDBACK_TAGS = [
  { value: "general", label: "일반", color: "#6b7280", bg: "#f3f4f6" },
  { value: "bug", label: "🐛 버그", color: "#991b1b", bg: "#fef2f2" },
  { value: "ux", label: "🎨 UX", color: "#1d4ed8", bg: "#eff6ff" },
  { value: "idea", label: "💡 아이디어", color: "#065f46", bg: "#f0fdf4" },
  { value: "urgent", label: "🔥 긴급", color: "#92400e", bg: "#fffbeb" },
] as const;
export type FeedbackTag = "general" | "bug" | "ux" | "idea" | "urgent";

export const PRODUCT_TYPES_META: Record<string, { label: string; code: string; hasLanguage: boolean; languageOptional?: boolean }> = {
  translation:    { label: "번역",      code: "TR", hasLanguage: true },
  interpretation: { label: "통역",      code: "IN", hasLanguage: true },
  combined:       { label: "통번역",    code: "CO", hasLanguage: true },
  proofreading:   { label: "감수",      code: "PR", hasLanguage: true },
  equipment:      { label: "통역장비",  code: "EQ", hasLanguage: false },
  editing:        { label: "편집/DTP",  code: "ED", hasLanguage: false },
  media:          { label: "미디어",    code: "MD", hasLanguage: true, languageOptional: true },
  operations:     { label: "운영/실비", code: "OP", hasLanguage: false },
  project:        { label: "프로젝트",  code: "PJ", hasLanguage: false },
};

/** 언어 선택이 필수인 유형인지 여부 (media는 optional이므로 false) */
export function isLangRequired(productType: string): boolean {
  const m = PRODUCT_TYPES_META[productType];
  return !!m?.hasLanguage && !m?.languageOptional;
}

export const MAIN_CATEGORIES_BY_TYPE: Record<string, { label: string; code: string }[]> = {
  translation: [
    { label: "일반번역", code: "GEN"  },
    { label: "전문번역", code: "SPEC" },
    { label: "출판번역", code: "PUB"  },
    { label: "번역공증", code: "CERT" },
    { label: "영상번역", code: "VID"  },
    { label: "자막번역", code: "SUB"  },
    { label: "SW번역",   code: "SW"   },
    { label: "기타번역", code: "ETC"  },
  ],
  interpretation: [
    { label: "일반통역",    code: "GEN"  },
    { label: "동시통역",    code: "SIM"  },
    { label: "순차통역",    code: "CON"  },
    { label: "위스퍼링통역", code: "WHP" },
    { label: "수행통역",    code: "ESC"  },
    { label: "VIP수행통역", code: "VIP"  },
    { label: "가이드통역",  code: "GID"  },
    { label: "미팅통역",    code: "MTG"  },
    { label: "전시회통역",  code: "EXH"  },
    { label: "화상통역",    code: "VDEO" },
    { label: "전화통역",    code: "TEL"  },
    { label: "기타통역",    code: "ETC"  },
  ],
  combined: [
    { label: "일반통번역",  code: "GEN"   },
    { label: "출장통번역",  code: "BIZ"   },
    { label: "전시회통번역", code: "EXPO" },
    { label: "상담회통번역", code: "MTG"  },
    { label: "IR통번역",   code: "IR"    },
    { label: "기타통번역",  code: "ETC"   },
    // 레거시 (기존 DB 저장값 표시용)
    { label: "일반번역", code: "GEN_L"  },
    { label: "전문번역", code: "SPEC_L" },
    { label: "동시통역", code: "SIM_L"  },
    { label: "순차통역", code: "CON_L"  },
    { label: "기타",     code: "ETC_L"  },
  ],
  proofreading: [
    { label: "감수",      code: "PRF" },
    { label: "원어민감수", code: "NAT" },
    { label: "AI감수",   code: "AI"  },
    { label: "기타감수",  code: "ETC" },
  ],
  equipment: [
    { label: "동시통역장비", code: "SIM" },
    { label: "가이드장비",   code: "GID" },
    { label: "위스퍼링장비", code: "WHP" },
    { label: "마이크장비",   code: "MIC" },
    { label: "음향장비",     code: "AUD" },
    { label: "부스장비",     code: "BTH" },
    { label: "운영장비",     code: "OPR" },
    { label: "기타장비",     code: "ETC" },
  ],
  editing: [
    { label: "편집/DTP", code: "EDT" },
  ],
  media: [
    { label: "미디어", code: "MED" },
  ],
  operations: [
    { label: "교통비",   code: "TX"   },
    { label: "식대",     code: "MEAL" },
    { label: "숙박",     code: "ACC"  },
    { label: "기타실비", code: "ETC"  },
  ],
  project: [
    { label: "번역프로젝트",   code: "TR"   },
    { label: "통역프로젝트",   code: "IN"   },
    { label: "종합언어서비스", code: "COMP" },
    { label: "기타프로젝트",   code: "ETC"  },
  ],
};

export const SUB_CATEGORIES_BY_MAIN: Record<string, { label: string; code: string; description?: string }[]> = {
  "전문번역": [
    { label: "법률",   code: "LAW"  },
    { label: "의료",   code: "MED"  },
    { label: "기술",   code: "TECH" },
    { label: "금융",   code: "FIN"  },
    { label: "계약서", code: "CONT" },
    { label: "논문",   code: "ACAD" },
  ],
  "감수": [
    { label: "원어민감수",   code: "NAT" },
    { label: "윤문",         code: "POL" },
    { label: "원문대조감수", code: "CMP" },
  ],
  "미디어": [
    { label: "STT",         code: "STT", description: "음성→텍스트"      },
    { label: "TTS",         code: "TTS", description: "텍스트→음성"      },
    { label: "자막작업",    code: "SUB", description: "Subtitle"         },
    { label: "녹취록",      code: "TRN", description: "Transcription"    },
    { label: "영상편집",    code: "VED", description: "Video Editing"    },
    { label: "더빙",        code: "DUB", description: "음성교체"         },
    { label: "영상번역",    code: "VTR", description: "Video Translation" },
    { label: "스크립트작성", code: "SCR", description: "대본작성"        },
    { label: "기타미디어",  code: "ETC"                                   },
  ],
  "편집/DTP": [
    { label: "편집",    code: "EDT" },
    { label: "DTP",     code: "DTP" },
    { label: "인쇄",    code: "PRT" },
    { label: "디자인",  code: "DSN" },
    { label: "PPT작업", code: "PPT" },
    { label: "기타편집", code: "ETC" },
  ],
  "동시통역장비": [
    { label: "FM장비",    code: "FM"  },
    { label: "적외선장비", code: "IR"  },
    { label: "리시버",    code: "RCV" },
    { label: "송신기",    code: "TRX" },
  ],
  "가이드장비": [
    { label: "가이드수신기", code: "RCV" },
    { label: "가이드송신기", code: "TRX" },
  ],
  "위스퍼링장비": [
    { label: "위스퍼링수신기", code: "RCV" },
    { label: "위스퍼링송신기", code: "TRX" },
  ],
  "마이크장비": [
    { label: "무선마이크",   code: "WLS" },
    { label: "유선마이크",   code: "WRD" },
    { label: "핀마이크",     code: "PIN" },
    { label: "회의용마이크", code: "CNF" },
  ],
  "음향장비": [
    { label: "오디오인터페이스", code: "AOI" },
    { label: "믹서",            code: "MIX" },
    { label: "음향콘솔",        code: "CON" },
    { label: "분배기",          code: "DST" },
  ],
  "부스장비": [
    { label: "통역부스", code: "BTH" },
    { label: "사전설치", code: "PRE" },
  ],
  "교통비": [
    { label: "항공료",   code: "AIR"  },
    { label: "KTX/기차", code: "RAIL" },
    { label: "택시비",   code: "TAXI" },
    { label: "톨비",     code: "TOLL" },
    { label: "렌터카",   code: "RNT"  },
    { label: "주유비",   code: "FUEL" },
    { label: "기타교통", code: "ETC"  },
  ],
  "식대": [
    { label: "식비",     code: "MEAL" },
    { label: "조식",     code: "BRK"  },
    { label: "중식",     code: "LCH"  },
    { label: "석식",     code: "DNN"  },
    { label: "기타식대", code: "ETC"  },
  ],
  "숙박": [
    { label: "호텔",    code: "HTL" },
    { label: "숙박",    code: "ACC" },
    { label: "기타숙박", code: "ETC" },
  ],
  "기타실비": [
    { label: "퀵",             code: "QCK"  },
    { label: "우편",           code: "POST" },
    { label: "인쇄",           code: "PRT"  },
    { label: "제본",           code: "BND"  },
    { label: "출장비",         code: "BIZ"  },
    { label: "엔지니어 출장비", code: "ENG" },
    { label: "장비운송비",     code: "TRN"  },
    { label: "기타실비",       code: "ETC"  },
  ],
};

export const LANGUAGE_CODES: { code: string; label: string }[] = [
  { code: "ko",      label: "한국어" },
  { code: "en",      label: "영어" },
  { code: "ja",      label: "일본어" },
  { code: "zh",      label: "중국어" },
  { code: "zh-hans", label: "중국어(간체)" },
  { code: "zh-hant", label: "중국어(번체)" },
  { code: "yue",     label: "광동어" },
  { code: "vi",      label: "베트남어" },
  { code: "th",      label: "태국어" },
  { code: "id",      label: "인도네시아어" },
  { code: "mn",      label: "몽골어" },
  { code: "ru",      label: "러시아어" },
  { code: "uz",      label: "우즈베크어" },
  { code: "ar",      label: "아랍어" },
  { code: "es",      label: "스페인어" },
  { code: "de",      label: "독일어" },
  { code: "fr",      label: "프랑스어" },
  { code: "it",      label: "이탈리아어" },
  { code: "pt",      label: "포르투갈어" },
  { code: "uk",      label: "우크라이나어" },
  { code: "pl",      label: "폴란드어" },
  { code: "nl",      label: "네덜란드어" },
  { code: "sv",      label: "스웨덴어" },
  { code: "cs",      label: "체코어" },
  { code: "tr",      label: "터키어" },
  { code: "el",      label: "그리스어" },
  { code: "fa",      label: "페르시아어" },
  { code: "he",      label: "히브리어" },
  { code: "hi",      label: "힌디어" },
  { code: "ur",      label: "우르두어" },
  { code: "bn",      label: "벵골어" },
  { code: "ta",      label: "타밀어" },
  { code: "my",      label: "미얀마어" },
  { code: "km",      label: "캄보디아어" },
  { code: "lo",      label: "라오어" },
  { code: "ms",      label: "말레이어" },
  { code: "custom",  label: "기타 직접입력" },
];

export const EQUIPMENT_QUANTITY_UNITS = ["개", "세트", "부스", "건"] as const;
export const EQUIPMENT_USAGE_PERIODS = ["반일", "1일", "2일", "3일"] as const;
export const INTERPRETATION_DIRECTIONS = ["양방향", "A→B", "B→A"] as const;

export const UNITS_BY_PRODUCT_TYPE: Record<string, string[]> = {
  translation:    ["어절", "단어", "글자", "페이지", "건"],
  interpretation: ["1시간", "2시간", "4시간", "6시간", "8시간", "추가시간"],
  combined:       ["어절", "단어", "글자", "페이지", "건", "1시간", "2시간", "4시간", "6시간", "8시간", "추가시간"],
  proofreading:   ["어절", "단어", "글자", "페이지", "건"],
  equipment:      ["대", "일", "건"],
  editing:        ["페이지", "건", "시간"],
  media:          ["분", "초", "건"],
  operations:     ["건", "인"],
  project:        ["건", "식"],
};

export const EQUIPMENT_ITEMS: string[] = [
  "FM장비",
  "적외선장비",
  "리시버",
  "송신기",
  "가이드수신기",
  "가이드송신기",
  "위스퍼링수신기",
  "위스퍼링송신기",
  "무선마이크",
  "유선마이크",
  "핀마이크",
  "회의용마이크",
  "오디오인터페이스",
  "믹서",
  "음향콘솔",
  "분배기",
  "통역부스",
  "사전설치",
  "기타 직접입력",
];

export const PRODUCT_MAIN_CATEGORIES = [
  // translation
  "일반번역", "전문번역", "출판번역", "번역공증", "영상번역", "자막번역", "SW번역", "기타번역",
  // interpretation
  "동시통역", "순차통역", "위스퍼링통역", "수행통역", "VIP수행통역", "가이드통역", "미팅통역", "전시회통역", "화상통역", "전화통역", "기타통역",
  // combined
  // proofreading
  "감수",
  // media
  "미디어",
  // equipment
  "동시통역장비", "가이드장비", "위스퍼링장비", "마이크장비", "음향장비", "부스장비", "운영장비", "기타장비",
  // editing
  "편집/DTP",
  // operations
  "교통비", "식대", "숙박", "기타실비",
  // project
  "번역프로젝트", "통역프로젝트", "종합언어서비스", "기타프로젝트",
] as const;
export type ProductMainCategory = typeof PRODUCT_MAIN_CATEGORIES[number];

export const PRODUCT_SUB_CATEGORIES: Record<string, string[]> = {
  "전문번역":   ["법률", "의료", "기술", "금융", "계약서", "논문"],
  "감수":       ["원어민감수", "윤문", "원문대조감수"],
  "미디어":     ["자막작업", "더빙", "영상번역", "스크립트작성", "STT", "TTS"],
  "편집/DTP":   ["편집", "DTP", "인쇄", "디자인", "PPT작업"],
  "동시통역장비": ["FM장비", "적외선장비", "리시버", "송신기"],
  "가이드장비":  ["가이드수신기", "가이드송신기"],
  "위스퍼링장비": ["위스퍼링수신기", "위스퍼링송신기"],
  "마이크장비":  ["무선마이크", "유선마이크", "핀마이크", "회의용마이크"],
  "음향장비":    ["오디오인터페이스", "믹서", "음향콘솔", "분배기"],
  "부스장비":    ["통역부스", "사전설치"],
  "교통비":     ["항공료", "KTX/기차", "택시비", "톨비", "렌터카", "주유비"],
  "식대":       ["식비", "조식", "중식", "석식", "기타식대"],
  "숙박":       ["호텔", "숙박", "기타숙박"],
  "기타실비":   ["퀵", "우편", "인쇄", "제본", "출장비", "엔지니어 출장비", "장비운송비", "기타실비"],
};

export const PRODUCT_UNITS = ["어절", "단어", "글자", "페이지", "건", "1시간", "2시간", "4시간", "6시간", "8시간", "추가시간", "대", "일", "박", "인", "분", "초", "시간"] as const;
export type ProductUnit = typeof PRODUCT_UNITS[number];

// 구버전 통역 단위 → 신규 단위 정규화 (반일→4시간, 종일→8시간)
const INTERP_UNIT_LEGACY: Record<string, string> = { "반일": "4시간", "종일": "8시간" };
export function normalizeInterpUnit(u: string): string {
  return INTERP_UNIT_LEGACY[u] ?? u;
}

export const PRODUCT_OPTION_TYPES = ["언어", "방식", "시간", "기타"] as const;
